#!/bin/tcsh -f
#
# NetStart v. 1.0c
#
# VERSION: 26 May 2003, K. Rapacki
#
# *****************************************************************************
# ******* *******            EDIT TO SUIT YOUR SITE             ******* *******
# full path to the NetStart-1.0 directory (mandatory)
setenv	NSHOME		/mnt/recherche/uORF/netstart/netstart-1.0c
# determine platform (do not change this unless you don't have 'uname'!)
set	SYSTEM		= `uname -s`
#
#setenv	SYSTEM	Linux
#SYSTEM="Linux"
# select AWK executable
# if ( $SYSTEM == "IRIX" ) then
#    setenv AWK /usr/bin/nawk
# else if ( $SYSTEM == "IRIX64" ) then
#    setenv AWK /usr/bin/nawk
# else if ( $SYSTEM == "SunOS" ) then
#    setenv AWK /bin/nawk
# if ( $SYSTEM == "Linux" ) then
#    setenv AWK /usr/bin/gawk
# else if ( $SYSTEM == "OSF1" ) then
#    setenv AWK /bin/nawk
# endif
setenv	AWK		/usr/bin/gawk
#setenv	GAWK	/usr/bin/gawk
#setenv	NAWK	/usr/bin/nawk
#
echo $NSHOME
echo $AWK
# override the above setting with your own terrific AWK ;-)
#setenv AWK     mysuperawk
#
# ECHO: avoid using the shell built-in echo command
#setenv	ECHO		/usr/bin/echo
if ( $SYSTEM == "Linux" ) then
	setenv ECHO echo
else
	setenv ECHO /usr/bin/echo
endif
#setenv ECHO /usr/bin/echo
#
# ******* *******      NO CHANGES EXPECTED BELOW THIS LINE      ******* *******
# *****************************************************************************
setenv	NSBIN		/mnt/recherche/uORF/netstart/netstart-1.0c/bin
setenv	NSETC		/mnt/recherche/uORF/netstart/netstart-1.0c/etc
setenv	NSSYN		/mnt/recherche/uORF/netstart/netstart-1.0c/syn
setenv	NSTMP		/mnt/recherche/uORF/netstart/netstart-1.0c/tmp/$$
echo $NSBIN
echo $NSETC
echo $NSSYN
echo $NSTMP
#
set	t_opt		= vert		# default: vertebrate sequences
set	infile				# default: stdin
set	ending		= s		# default: plural ending
#
# command line ================================================================
while ( $1 != "" )
	echo "hello"
	switch ( $1 )  #correspond a des if successifs
		case "-at":
			set t_opt = at
			breaksw
		case "-h":
			set h_opt
			breaksw
		case "-vert":
			set t_opt = vert
			breaksw
		default:
			set infile = ($infile $1)
			breaksw
	endsw
	shift
end
#
if ( $?h_opt ) then					# help on usage
	$ECHO usage: netstart \[-at\|-vert\] \[\<file\> ...\]
	exit 0

else if ( $#infile ) then                               # check infile(s)
        foreach f ($infile)
                if ( ! -e $f ) then     # infile not found
                        echo netstart: \"$f\" not found
                        exit -1
                endif
        end
endif

mkdir $NSTMP						# Ol Korrect ...
echo $NSTMP

# prepare input file in HOW format ============================================
(cat $infile | $AWK -f $NSBIN/fasta2how >$NSTMP/infile) >&/dev/null

set	infile	= $NSTMP/infile
@	ecount	= `grep '[0-9] [^ ]' $infile | wc -l`

if ( $ecount == 0 ) then
	exit 0
else if ( $ecount == 1 ) then
	set ending
endif

#
# MAIN ========================================================================
cd $NSTMP

if ( $t_opt == "at" ) then
	set type = 'dicot plant'
else
	set type = vertebrate
endif

set nshome = `$ECHO $NSHOME | sed 's/\//\\\//g'`	# escape '/':s in name

$ECHO '\n'Translation start predictions for $ecount $type sequence$ending

cat $NSETC/par.how | \
	sed 's/__NUM__/'$ecount'/;s/__SYN__/'$t_opt'/;s/__NS__/'$nshome'/' | \
	$NSBIN/how98_`uname` | $AWK -f $NSBIN/pp


# cleanup =====================================================================
cd /
rm -r $NSTMP

#
# end of script ===============================================================
